services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3  # Adjust based on your database setup
